name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0 # Specify the Node.js version your project uses

      # Step 3: Install dependencies and build
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Step 4: Deploy to EC2, make sure to add a .pem key file in secrets and variables.
      - name: Deploy to EC2
        env:
          TEST_KEY: ${{ secrets.TEST_KEY }}
          HOST: 13.234.231.217 # Replace with your EC2 instance's public IP
          USER: ubuntu # Replace with the EC2 instance username if different
        run: |
          # Write the SSH private key to a file
          echo "$TEST_KEY" > key.pem
          chmod 600 key.pem

          # Ensure the directory exists and has the right permissions
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "sudo mkdir -p /home/ubuntu/blogs && sudo chown -R $USER:$USER /home/ubuntu/blogs && sudo chmod -R u+rwx /home/ubuntu/blogs"

            # Copy build files to EC2 instance
          scp -o StrictHostKeyChecking=no -i key.pem -r dist/* $USER@$HOST:/home/ubuntu/blogs

          # Restart nginx to serve the new build
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "sudo systemctl restart nginx"
